schema_version = "1"

[entrypoint]
scenario = "baseline"
runtime = "local-dimod"
runtime_options = { sampler = "exact" }
# runtime = "qiskit"
# runtime_options = { fake_backend = "FakeFez" }

[scenarios.baseline]
problem = "SimpleSubset"

[scenarios.baseline.sets]
Elements = ["e1", "e2", "e3", "e4", "e5", "e6"]

[scenarios.baseline.params.Value]
e1 = 1
e2 = 1
e3 = 1
e4 = 1
e5 = 1
e6 = 1
